FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8001

ENV PORT=8001
CMD ["uvicorn", "llamaServer:app", "--host", "0.0.0.0", "--port", "8001"] 