name: Deploy All Services

on:
  push:
    branches: [ main ]

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build & Push Flask AI
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/flask-ai:latest ./Flask
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flask-ai:latest

      - name: Build & Push Gateway Service
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/gateway-service:latest ./GateWay
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/gateway-service:latest

      - name: Build & Push Core Service
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/core-service:latest ./CoreService
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/core-service:latest

      - name: Build & Push Assist Service
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/assist-service:latest ./AssistService
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/assist-service:latest

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest ./vite-react-teamsketch
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

      - name: Build & Push Nginx
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/nginx:latest ./nginx
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nginx:latest

  deploy:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
            
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/flask-ai:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/gateway-service:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/core-service:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/assist-service:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/nginx:latest
            
            docker-compose down
            docker-compose up -d
