name: Run on Self-Hosted

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: self-hosted

    steps:
      - name: Set PowerShell Execution Policy
        shell: pwsh
        run: Set-ExecutionPolicy RemoteSigned -Scope Process -Force

      - name: Run a script using Bash
  	shell: bash
  	run: echo "✅ GitHub Actions이 로컬에서 실행됨!"
